stages:
  - build
  - docker

cache:
  key: "$CI_BUILD_REF_NAME-$CI_BUILD_REF"
  paths:
    - target/bookStore-*.jar

job_build:
  image: maven:3-jdk-9
  stage: build
  script:
    - mvn package
  variables:
    MAVEN_OPTS: -Dmaven.repo.local=/cache/maven/repository

  tags:
    - docker

job_docker_build:
  image: gitlab/dind
  stage: docker
  
  only:
    - master
  
  script: 
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN hub.githost.io
    - docker build -t hub.githost.io/malinovsky/tolstolutskyi_bookstore .
    - docker push hub.githost.io/malinovsky/tolstolutskyi_bookstore

  dependencies:
    - job_build
  
  tags:
    - dind

job_docker_tag:
  image: gitlab/dind
  stage: docker

  only:
    - tags


  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN hub.githost.io
    - docker build -t hub.githost.io/malinovsky/tolstolutskyi_bookstore .
    - docker tag hub.githost.io/teleg/socialnet hub.githost.io/malinovsky/tolstolutskyi_bookstore:$CI_COMMIT_TAG
    - docker push hub.githost.io/malinovsky/tolstolutskyi_bookstore:$CI_COMMIT_TAG

  dependencies:
    - job_build

  tags:
    - dind
