version: '3'

services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    ports:
      - 5435:5432
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=bookstore
      - POSTGRES_INITDB_ARGS="--encoding=utf8"
    volumes:
      - volume-postgres:/bitnami

volumes:
  volume-postgres:
