version: '3'

networks:
  network1:

services:
  server:
    depends_on:
      - postgresql
    build:
      context: ./
      dockerfile: Dockerfile
    image: bookstore
    ports:
      - 8090:8090
    networks:
      - network1
    environment:
      - jdbcUrl=jdbc:postgresql://postgresql/bookstore
      - port=8090
      - dbUsername=postgres
      - dbPassword=postgres
      - SPA=prod
  postgresql:
    image: postgres
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_REPLICATION_MODE=master
      - POSTGRES_REPLICATION_USER=repl_user
      - POSTGRES_REPLICATION_PASSWORD=repl_password
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=bookstore
      - POSTGRES_INITDB_ARGS="--encoding=utf8"
    volumes:
      - ./init/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network1

volumes:
    init:
