spring:
  profiles:
    active: dev
  application:
    name: bookstore
  liquibase:
    change-log: classpath:schema/changelog.xml
  security:
    resourceId: bookstore
    basic:
      enabled: false
    jwtSignature: 123456
    client: bookstore_client
    secret: bookstore_secret
    accessTokenValiditySeconds: 600
    refreshTokenValiditySeconds: 1209600 # two weeks

cloudinary:
    cloudName: do9a3u2vv
    apiKey: 145895683742271
    apiSecret: XfmsJQwf5v6c9guD-f0C2msT9oU

server:
  port: 8090

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/bookstore
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
---
spring:
  profiles: prod
  datasource:
    url: ${jdbcUrl}
    username: ${dbUsername}
    password: ${dbpassword}
    driver-class-name: org.postgresql.Driver
server:
  port: ${port}