spring:
  profiles:
    active: dev
  application:
    name: bookstore
  liquibase:
    change-log: classpath:schema/changelog.xml
  security:
    basic:
      enabled: false
    jwtSignature: 123456
    defaultClient: book-shop
    accessTokenValiditySeconds: 60 #one minute
    refreshTokenValiditySeconds: 1209600 # two weeks

server:
  port: 8090
  servlet:
    context-path: /bookstore

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5435/bookstore
    username: postgres
    password: postgres