spring:
  profiles:
    active: dev
  application:
    name: bookstore
  liquibase:
    change-log: classpath:schema/changelog.xml
  security:
    resourceId: bookstore
    basic:
      enabled: false
    jwtSignature: 123456
    defaultClient: bookstore_client
    accessTokenValiditySeconds: 600
    refreshTokenValiditySeconds: 1209600 # two weeks

server:
  port: 8090

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5435/bookstore
    username: postgres
    password: postgres